version: "3.8"

services:
  db:
    image: nlpsandbox/postgres:1.0.0
    container_name: data-node-db
    restart: always
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DB}
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
    - ${SQL_PORT}:5432

  api:
    image: nlpsandbox/data-node-i2b2-2014:0.1.0
    build:
      context: server
      dockerfile: Dockerfile
    container_name: data-node-api
    environment:
      - SERVER_PROTOCOL
      - SERVER_DOMAIN
      - SERVER_PORT
      - SQL_USER
      - SQL_PASSWORD
      - SQL_HOST
      - SQL_DB
      - SQL_PORT
      - SYNAPSE_USERNAME
      - SYNAPSE_API_KEY
      - DATA_SYNAPSE_ID
      - DATA_MD5
      - GOLDSTANDARD_SYNAPSE_ID
      - GOLDSTANDARD_MD5
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      - db

volumes:
    database-data:
