version: "3.8"

services:
  database:
    build:
          context: .
          dockerfile: Dockerfile_PG
    container_name: pg_db
    restart: always
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "6000:5432"

  api:
    build:
      context: flask-app
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - database.env
    ports:
      - "80:8080"
    depends_on:
      - database
volumes:
    database-data:

