version: "3.8"

services:
  database:
    build:
          context: .
          dockerfile: Dockerfile_PG
    container_name: pg_db
    restart: always
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "6000:5432"

volumes:
    database-data:

#  api:
#    build:
#      context: .
#      dockerfile: dockerfile
#    container_name: api
#    environment:
#      SYNAPSE_USERNAME: ${SYNAPSE_USERNAME}
#      SYNAPSE_APIKEY: '${SYNAPSE_APIKEY}'
#    ports:
#      - "80:8080"
#    depends_on:
#      - db